// ─────────────────────────────────────────────────────────────────────────
// generate-palette.ts — headless, model-only palette generator.
// Usage:
//   node scripts/generate-palette.ts --base "oklch(0.55 0.12 162)" \
//        [--saturation default] [--neutral-hue 162]
// Emits the DESIGN.md `colors:` palette block (stdout) + an APCA report (stderr).
// ─────────────────────────────────────────────────────────────────────────
import { generateAll, parseColor, apca, oklchToSrgb01, type Step } from "../src/lib/oklch.ts";

function arg(name: string, def?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}

const baseStr = arg("base");
if (!baseStr) {
  console.error('Required: --base "oklch(L C H)" or --base "#RRGGBB"');
  process.exit(1);
}
const base = parseColor(baseStr); // accepts oklch(...) OR a hex string
if (!base) { console.error(`Could not parse: ${baseStr}`); process.exit(1); }

const saturation = arg("saturation", "default")!;
const neutralHue = arg("neutral-hue");
const neutralChroma = arg("neutral-chroma"); // warmth/tint intensity, default 0.25

const p = generateAll({
  base,
  saturation,
  neutralHue: neutralHue ? parseFloat(neutralHue) : undefined,
  neutralChromaScale: neutralChroma ? parseFloat(neutralChroma) : undefined,
});

const ind = (n: number) => " ".repeat(n);
const lines: string[] = ["  # Generated by generate-palette.ts — do not hand-edit.", "colors:"];

function emit(name: string, pal: { light: Step[]; dark: Step[] }, baseStr?: string, hue?: number) {
  lines.push(`  ${name}:`);
  if (baseStr) lines.push(`${ind(4)}base: "${baseStr}"`);
  if (hue !== undefined) lines.push(`${ind(4)}hue: ${hue}`);
  pal.light.forEach((s) => lines.push(`${ind(4)}${s.step}:${s.step < 10 ? "  " : " "}"${s.oklch}"`));
  lines.push(`${ind(4)}dark:`);
  pal.dark.forEach((s) => lines.push(`${ind(6)}${s.step}:${s.step < 10 ? "  " : " "}"${s.oklch}"`));
}

emit("primary", p.primary, base ? `oklch(${base.L} ${base.C} ${base.H})` : undefined);
emit("neutral", p.neutral, undefined, neutralHue ? parseFloat(neutralHue) : base.H);
emit("success", p.success, "oklch(0.55 0.13 145)");
emit("warning", p.warning, "oklch(0.72 0.15 75)");
emit("danger",  p.danger,  "oklch(0.55 0.20 25)");

process.stdout.write(lines.join("\n") + "\n");

// ── APCA report → stderr ──────────────────────────────────────────────────
function lc(a: Step, bg: Step): number {
  return apca(oklchToSrgb01(a.L, a.C, a.H), oklchToSrgb01(bg.L, bg.C, bg.H));
}
const white: [number, number, number] = [1, 1, 1];
const rep: string[] = ["", "── APCA report ──"];
for (const [name, pal] of Object.entries(p)) {
  const s = pal.light;
  const cta = s[8];
  const wob = apca(white, oklchToSrgb01(cta.L, cta.C, cta.H));
  rep.push(
    `${name.padEnd(8)} step9 ${cta.hex}  white-on-CTA Lc ${wob.toFixed(0).padStart(3)}  ` +
    `text11/step2 Lc ${lc(s[10], s[1]).toFixed(0)}  text12/step2 Lc ${lc(s[11], s[1]).toFixed(0)}`
  );
}
process.stderr.write(rep.join("\n") + "\n");
